export const data = [
  {
    title: "Next.js Store Project 111",
    description: "Technologies used in this project:",
    imageUrl: "./assets/IMG_6770.JPG",
    technologies: [
      "/assets/nextjs-icon.png",
      "/assets/typescript-icon.png",
      "/assets/tailwind-icon.png",
      "/assets/prism-icon.png",
    ],
    projectLink: "#",
    codeLink: "#",
  },
  {
    title: "Next.js Store Project 222",
    description: "Technologies used in this project:",
    imageUrl: "./assets/IMG_6770.JPG",
    technologies: [
      "/assets/nextjs-icon.png",
      "/assets/typescript-icon.png",
      "/assets/tailwind-icon.png",
      "/assets/prism-icon.png",
    ],
    projectLink: "#",
    codeLink: "#",
  },
  {
    title: "Next.js Store Project 333",
    description: "Technologies used in this project:",
    imageUrl: "./assets/IMG_6770.JPG",
    technologies: [
      "/assets/nextjs-icon.png",
      "/assets/typescript-icon.png",
      "/assets/tailwind-icon.png",
      "/assets/prism-icon.png",
    ],
    projectLink: "#",
    codeLink: "#",
  },
  {
    title: "Next.js Store Project 444",
    description: "Technologies used in this project:",
    imageUrl: "./assets/IMG_6770.JPG",
    technologies: [
      "/assets/nextjs-icon.png",
      "/assets/typescript-icon.png",
      "/assets/tailwind-icon.png",
      "/assets/prism-icon.png",
    ],
    projectLink: "#",
    codeLink: "#",
  },
  {
    title: "Next.js Store Project 555",
    description: "Technologies used in this project:",
    imageUrl: "./assets/IMG_6770.JPG",
    technologies: [
      "/assets/nextjs-icon.png",
      "/assets/typescript-icon.png",
      "/assets/tailwind-icon.png",
      "/assets/prism-icon.png",
    ],
    projectLink: "#",
    codeLink: "#",
  },
  {
    title: "Next.js Store Project 666",
    description: "Technologies used in this project:",
    imageUrl: "./assets/IMG_6770.JPG",
    technologies: [
      "/assets/nextjs-icon.png",
      "/assets/typescript-icon.png",
      "/assets/tailwind-icon.png",
      "/assets/prism-icon.png",
    ],
    projectLink: "#",
    codeLink: "#",
  },
];
